@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant HttpServerAjax as Server <<http server>>
participant ShareBoardController as Controller <<application>>

database BoardRepository as Repository <<repository>>
participant BoardService as Service <<service>>


Actor --> Server: Writes the email address and the \naccess level to be given and pushes the button to add
activate Server




    Server -> Controller: shareBoard(boardId, userToBeAdded, boardOwner, accessLevel)

    activate Controller

     Controller -> SessionManager: getUserByToken(token)
        activate SessionManager
        SessionManager -> Controller: authUser
        deactivate SessionManager

    Controller -> Repository: ofIdentity(boardId)
    activate Repository
    Repository -> Controller: board
    deactivate Repository

   Controller -> Service : confirmLevel(accessLevel)
   activate Service
   Service -> Controller : AccessLevel
    deactivate Service

    Controller -> Service : shareBoard(boardId, userToBeAdded, accessLevel)
activate Service
Service -> Board : userHasPermission(userToBeAdded, accessLevel)
activate Board
Board -> Service : boolean
deactivate Board

Service -> Board : userHasPermission(userToBeAdded, differentLevel)
activate Board
Board -> Service : boolean
deactivate Board

Service -> Board : addPermission(userToBeAdded, accessLevel)
activate Board
Board -> Service : boardPermission
deactivate Board

Service -> BoardRepository : save(Board)
activate BoardRepository
BoardRepository -> Service : board
deactivate BoardRepository

Service -> Controller : boardPermission
deactivate Service

    Controller -> Server: boardPermission
    deactivate Controller

    Server --> Actor: confirmation

deactivate Server
@enduml