@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant MainMenuUI as UI <<presentation>>
participant SharedBoardAppController as Controller <<application>>
participant MessageFormat as MF <<util>>

Actor --> UI: End of session request
activate UI
    UI -> Controller: create(sock)

    Controller -> MF: create(sock)
    activate Controller
    UI -> Controller: sendEndOfSession()

    Controller -> MF: sendMessage(VERSION, MessageCodes.DISCONN, "")

    Controller -> MF: readMessage()
    activate MF
    MF -> Controller: result
    deactivate MF

    Controller -> UI: result
    deactivate Controller



    UI --> Actor: displayEndOfSessionSuccessfully

deactivate UI
@enduml