@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Manager as Actor
participant ListUsersUI as UI <<presentation>>
participant ListUsersController as Controller <<application>>
participant AuthorizationService as AuthzService <<service>>
participant UserManagementService as Service <<service>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database UserRepository as Repository <<repository>>


Actor --> UI: List Users
activate UI
    UI -> Controller: create()

    UI -> Controller: listAllUsers()
    activate Controller

    Controller -> AuthzService: create()
    activate AuthzService
    Controller -> AuthzService: ensureAuthenticatedUserHasAnyOf(CourseRoles.MANAGER)
    deactivate AuthzService

    Controller -> Service: create()
    activate Service
    Controller -> Service: allUsers()


        Service -> Persistence: repositories()
        activate Persistence
        Persistence -> Factory: create()
        Persistence -> Service: factory
        deactivate Persistence

        Service -> Factory: users()
        activate Factory
        Factory -> Repository: create()
        Factory -> Service: userRepository
        deactivate Factory

        Service -> Repository: findAll()
        activate Repository
        Repository -> Service: allUsers
        deactivate Repository

        Service -> Controller: allUsers
        deactivate Service
        Controller -> UI: allUsers
        deactivate Controller

        UI -> UI: show()
        UI -> Actor: back to menu

deactivate UI
@enduml