@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant HttpServerAjax as Server <<http server>>
participant UpdatePostItController as Controller <<application>>
participant SessionManager as SM
participant PostItService as Service <<service>>
participant PostItFactory as PFactory <<factory>>
participant PostIt as Domain <<domain>>
database PostItRepository as Repository <<repository>>
database BoardRepository as RepositoryB <<repository>>


Actor --> Server: Update Post-It Content
activate Server
    Server -> Controller: create()
    Server -> SM: create()

    Server --> Actor: Ask post-it information
    Actor --> Server: PostItContent, PostItRow, PostItColumn, BoardId


    Server -> SM: getUserByToken(token)
    activate SM
    SM -> Server: authUser
    deactivate SM
        
    Server -> Controller: updatePostItContent(postItContent, postItRow,\npostItColumn, boardId, authUser)
    activate Controller


    Controller -> Service: create()
    note right: dependency injection was abastracted\nfor diagram readability

    Controller -> Service: changePostIt(postItContent, postItRow,\npostItColumn, boardId, authUser, PostItStateType.UPDATED)
    activate Service

        Service -> RepositoryB: ofIdentity(boardId)
        activate RepositoryB
        RepositoryB -> Service: board
        deactivate RepositoryB

        Service -> Service: checkIfIsRowEntryTitle(postItRow, board)
        Service -> Service: checkIfIsColumnEntryTitle(postItColumn, board)
        Service -> Service: postItByPosition(postItRow, postItColumn, board, false)
        Service -> Service: checkForUserOwnership(authUser, board, lastPostIt)


        Service -> PFactory: create()
        Service -> PFactory: createChange(postItContent, postItRow, postItColumn,\nauthUser, board, postItState, lastPostIt)
        activate PFactory

        PFactory -> Domain: PostIt(postItContent, postItRow, postItColumn,\npostItOwner, board, postItState, lastPostIt)
        activate Domain
            Domain -> PFactory: postItUpdated
        deactivate Domain
            PFactory -> Service: postItUpdated
        deactivate PFactory


        Service -> Repository: save(postItUpdated)
        activate Repository
        Repository -> Service: postItUpdated
        deactivate Repository

        Service -> Controller: postItUpdated
        deactivate Service
        Controller -> Server: postItUpdated
        deactivate Controller

        Server --> Actor: displayPostItUpdated

deactivate Server
@enduml